app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/welcome/WelcomeBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt, app/src/main/res/layout-sw600dp/bottom_sheet_map_style.xml, app/src/main/res/layout-sw600dp/bottom_sheet_welcome.xml, app/src/main/res/layout-sw600dp/fragment_map_style.xml, app/src/main/res/layout-sw600dp/fragment_setting.xml, app/src/main/res/layout-sw600dp/fragment_unit_system.xml, app/src/main/res/layout-sw720dp/bottom_sheet_map_style.xml, app/src/main/res/layout-sw720dp/bottom_sheet_welcome.xml, app/src/main/res/layout-sw720dp/fragment_map_style.xml, app/src/main/res/layout-sw720dp/fragment_setting.xml, app/src/main/res/layout-sw720dp/fragment_unit_system.xml, app/src/main/res/layout/fragment_map_style.xml, app/src/main/res/values-sw600dp-land/dimens.xml, app/src/main/res/values/strings.xml
Fix(Tablet): Unit screen design added for tablet and other bug fixes
=> Tablet design bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt, app/src/main/res/values/strings.xml
fix(MapStyle): Enable location icon for grab bug fixes
=> Enable location icon for grab bug fixes

app/build.gradle, app/src/androidTest/java/com/aws/amazonlocation/ConstantTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/bug/AfterSearchDirectionErrorExistsTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/bug/AfterSearchOutsideViewPortTest.kt, app/src/main/java/com/aws/amazonlocation/data/datasource/RemoteDataSourceImpl.kt, app/src/main/java/com/aws/amazonlocation/data/response/NavigationResponse.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CustomSpinnerAdapter.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/res/drawable/ic_down_arrow_green.xml, app/src/main/res/drawable/spinner_bg.xml, app/src/main/res/layout-sw600dp/bottom_sheet_cloud_formation.xml, app/src/main/res/layout-sw600dp/fragment_aws_cloud_information.xml, app/src/main/res/layout-sw600dp/fragment_explore.xml, app/src/main/res/layout-sw720dp/bottom_sheet_cloud_formation.xml, app/src/main/res/layout-sw720dp/fragment_aws_cloud_information.xml, app/src/main/res/layout-sw720dp/fragment_explore.xml, app/src/main/res/layout/bottom_sheet_cloud_formation.xml, app/src/main/res/layout/fragment_aws_cloud_information.xml, app/src/main/res/layout/fragment_explore.xml, app/src/main/res/layout/spinner_dropdown_item.xml, app/src/main/res/layout/spinner_item.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw720dp/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
fix(Settings): Bug fixes to avoid tolls and ferries
fix(MapStyle): Grab map style blank map bugfix
fix(RouteOption): Route option hide for a walk, bicycle, motorcycle
fix(Auth): Added region selection in cloud formation
=> Grab map style blank map and route option hide bug fixes and added region selection for sign in

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CustomSpinnerAdapter.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInViewModel.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/res/layout-sw600dp/bottom_sheet_cloud_formation.xml, app/src/main/res/layout-sw600dp/fragment_aws_cloud_information.xml, app/src/main/res/layout-sw720dp/bottom_sheet_cloud_formation.xml, app/src/main/res/layout-sw720dp/fragment_aws_cloud_information.xml, app/src/main/res/layout/bottom_sheet_cloud_formation.xml, app/src/main/res/layout/fragment_aws_cloud_information.xml, app/src/main/res/layout/spinner_item.xml, app/src/main/res/values/strings.xml
fix(Auth): Spinner design change for region selection
=> Spinner design change for region selection

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CustomSpinnerAdapter.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/res/layout/spinner_dropdown_item.xml, app/src/main/res/values/colors.xml
fix(Auth): Selected region highlight
fix(Search): My location click on search direction starts shimmer bug fix
fix(Geofence): Add geofence close icon click bug fix
=> Selected region highlight and auto starts shimmer bug fix

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/unit_system/UnitSystemFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt, app/src/main/res/layout-sw600dp/fragment_unit_system.xml, app/src/main/res/layout-sw720dp/fragment_unit_system.xml, app/src/main/res/layout/fragment_unit_system.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
fix(Metrics): Units metrics automatic label text added
fix(Search): My location auto-fill change
=> Units metrics automatic label text added

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleFragment.kt, app/src/main/res/layout-sw600dp/bottom_sheet_map_style.xml, app/src/main/res/layout-sw600dp/fragment_map_style.xml, app/src/main/res/layout-sw720dp/bottom_sheet_map_style.xml, app/src/main/res/layout-sw720dp/fragment_map_style.xml, app/src/main/res/layout/bottom_sheet_map_style.xml, app/src/main/res/layout/fragment_map_style.xml, app/src/main/res/values/strings.xml
- fix(MapStyle): clear filter added in map style search
=> Clear filter added in map style search

app/src/main/res/values-sw720dp/dimens.xml
fix(MapStyle): Map style dialog size increase
=> Map style dialog size increase

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/Units.kt, app/src/main/res/values/strings.xml
- Dynamically Localize Number Formats for International User Support added [ALS-1572](https://makeen.atlassian.net/browse/ALS-1572)
[ALS-1572]: https://makeen.atlassian.net/browse/ALS-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ALS-1572 - Localize number format

app/build.gradle, app/src/main/java/com/aws/amazonlocation/data/datasource/RemoteDataSourceImpl.kt
Upgraded AWS Amplify & cognito packages for this
=> ALS-590:  Implemented signout clear cache issue and upgraded package

app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- Tracking and geofence half expand ratio changed
=> Tracking and geofence half expand ratio changed

app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/data_provider/DataProviderFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/unit_system/UnitSystemFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
=> Analytics changes

app/src/androidTest/java/com/aws/amazonlocation/ui/main/CheckGrabGoButtonTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/CheckRouteOptionsTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/ExploreFragmentSearchByCategoriesTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/ExploreFragmentSearchLocationByAddressTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/ExploreFragmentSearchLocationByGeocodeTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/ExploreFragmentSearchResultTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/ExploreFragmentSearchTotalResultTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SearchAddressExactMatchPOICardLocationTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SearchPlaceDisplayedOnMapPOICircleTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SearchPlaceDisplayedOnMapTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SearchResultComparisonTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SimulationStartTrackingHistoryLoggedTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SimulationStopTrackingHistoryLoggedTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingAwsConnectTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingDeleteTrackingHistoryTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingGeofenceEnterTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingGeofenceExitTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingStartTrackingHistoryLoggedTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingStartTrackingMapDisplayTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingStartTrackingTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/TrackingStopTrackingTest.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- For different language link text bug fix
- E2E test cases bug fix
=> Language and E2E bug fixes

README.md, custom.properties.example
- README.md and .example files updated
=> README.md and .example files updated

app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/DialogUtils.kt, app/src/main/res/values-ar/string.xml, app/src/main/res/values-de/string.xml, app/src/main/res/values-es/string.xml, app/src/main/res/values-fr/string.xml, app/src/main/res/values-hi/string.xml, app/src/main/res/values-it/string.xml, app/src/main/res/values-iw/string.xml, app/src/main/res/values-ja/string.xml, app/src/main/res/values-ko/string.xml, app/src/main/res/values-pt/string.xml, app/src/main/res/values-zh-rCN/string.xml, app/src/main/res/values-zh-rTW/string.xml, app/src/main/res/values/strings.xml
- Tracking sheet not opening bug fix [ALS-1604](https://makeen.atlassian.net/browse/ALS-1604)
- Grab simulation and analytics bug fix
[ALS-1604]: https://makeen.atlassian.net/browse/ALS-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tracking sheet not opening bug fix

app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
https://makeen.atlassian.net/browse/ALS-1603
=> ALS-1603: Fixed Stack Corruption on Grab Search

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- Simulation map style change bug fix
=> Simulation map style change bug fix

app/src/main/java/com/aws/amazonlocation/ui/main/data_provider/DataProviderFragment.kt
- Add EU instance in the data provider screen
=> Add EU instance fixes

app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt
=> App instance tablet bug fix

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt, app/src/main/res/layout-sw600dp/bottom_sheet_start_simulation.xml, app/src/main/res/layout-sw720dp/bottom_sheet_start_simulation.xml, app/src/main/res/values-sw600dp-land/dimens.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw720dp-land/dimens.xml, app/src/main/res/values-sw720dp/dimens.xml, app/src/main/res/values/dimens.xml
- Open data map style bug fixes
=> Open data bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- Change style tracking sheet visible bug fix
=> Change style tracking sheet visible bug fix

README.md, custom.properties.example
=> README.md file updated

app/src/androidTest/java/com/aws/amazonlocation/ConstantTest.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SettingsFragmentAnalyticsTest.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/AnalyticsHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- Automatic region display name change
- Analytics E2E test case added
=> Automatic region display fix and analytics E2E test case added

app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/region/RegionFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- Region display changes
- Simulation does not complete the second time [ALS-1648](https://makeen.atlassian.net/browse/ALS-1648)
- Click here on how to connect to AWS does not work [ALS-1649](https://makeen.atlassian.net/browse/ALS-1649)
- Simulation starts after the map load bug fix
[ALS-1648]: https://makeen.atlassian.net/browse/ALS-1648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALS-1649]: https://makeen.atlassian.net/browse/ALS-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Region display, simulation, click here and start simulation after map load bug fixes

README.md, app/build.gradle, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/Units.kt, app/src/test/java/com/aws/amazonlocation/utils/units/UnitsGetSimulationWebSocketUrlTest.kt, custom.properties.example
- Simulation web socket URL fixes, README file updated, custom.properties.example file updated and Unit test case added
=> Simulation web socket URL fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
- Map zooms in on the destination point after switching destination point with starting point bug fix [ALS-1659](https://makeen.atlassian.net/browse/ALS-1659)
- User is able to see the map is a bit too much zoomed out bug fix [ALS-1661](https://makeen.atlassian.net/browse/ALS-1661)
[ALS-1659]: https://makeen.atlassian.net/browse/ALS-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALS-1661]: https://makeen.atlassian.net/browse/ALS-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Map zoom bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt, app/src/main/res/layout-sw600dp-land/bottom_sheet_tracking.xml, app/src/main/res/layout-sw600dp/bottom_sheet_tracking.xml, app/src/main/res/layout-sw720dp-land/bottom_sheet_tracking.xml, app/src/main/res/layout-sw720dp/bottom_sheet_tracking.xml, app/src/main/res/layout/bottom_sheet_tracking.xml
- Tracking UI bug fixes [ALS-1663](https://makeen.atlassian.net/browse/ALS-1663)
[ALS-1663]: https://makeen.atlassian.net/browse/ALS-1663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Tracking UI bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
- Session expired bug fix (unmarshal response fix)
=> Session expired fix

app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/Units.kt
- Pre-fix remove for websocket URL fix
=> Pre-fix remove for websocket URL fix

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/Units.kt, app/src/main/res/layout-sw600dp/bottom_sheet_direction_search.xml, app/src/main/res/layout-sw720dp/bottom_sheet_direction_search.xml, app/src/main/res/layout/bottom_sheet_direction_search.xml, app/src/test/java/com/aws/amazonlocation/mock/Constants.kt
- Search no data found can be shown in background fix [ALS-1675](https://makeen.atlassian.net/browse/ALS-1675) (point-2)
- No need to show 0 min if the hour is available  [ALS-1675](https://makeen.atlassian.net/browse/ALS-1675) (point-3)
- User can catch the geofence and tracking sheet after holding with a finger fix [ALS-1675](https://makeen.atlassian.net/browse/ALS-1675) (point-4)
[ALS-1675]: https://makeen.atlassian.net/browse/ALS-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALS-1675]: https://makeen.atlassian.net/browse/ALS-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ALS-1675]: https://makeen.atlassian.net/browse/ALS-1675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> Search no data found, geofence and tracking sheet catch and minute display fixes

app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- IdentityPoolId validation fixes
=> Validate Identity Pool Id bug fix

app/src/main/java/com/aws/amazonlocation/ui/main/attribution/AttributionFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- Broken display on attribution bug fix [ALS-1702](https://makeen.atlassian.net/browse/ALS-1702)
[ALS-1702]: https://makeen.atlassian.net/browse/ALS-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Broken display on attribution bug fix

app/src/main/java/com/aws/amazonlocation/ui/base/BaseActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/Units.kt, app/src/main/res/layout/bottom_sheet_direction_search.xml, app/src/main/res/values-ar/string.xml, app/src/main/res/values-de/string.xml, app/src/main/res/values-es/string.xml, app/src/main/res/values-fr/string.xml, app/src/main/res/values-hi/string.xml, app/src/main/res/values-it/string.xml, app/src/main/res/values-iw/string.xml, app/src/main/res/values-ja/string.xml, app/src/main/res/values-ko/string.xml, app/src/main/res/values-pt/string.xml, app/src/main/res/values-zh-rCN/string.xml, app/src/main/res/values-zh-rTW/string.xml, app/src/main/res/values/strings.xml
- Network disconnected bug fixes
- Search direction loader, swap, error message change, and other bug fixes
- Keyboard open on search and direction sheet
=> V2 bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreViewModel.kt
- Reduce search direction debounce time for the smooth swap and swap-related bug fix
- My Location label hides on direction error bug fix
=> Swap location and My location label hide on error

app/proguard-rules.pro, app/src/main/java/com/aws/amazonlocation/ui/base/BaseFragment.kt
-  App crash management with pro-guard [https://makeen.atlassian.net/browse/ALS-1704](ALS-1704)
=> ALS-1704 app crash manage with pro-guard

app/build.gradle
- App language change not working on production fix [ALS-1735](https://makeen.atlassian.net/browse/ALS-1735)
[ALS-1735]: https://makeen.atlassian.net/browse/ALS-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ALS-1735 App language production issue fix

app/build.gradle
- CF template update for different build types
=> CF template update for different build types

app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
fix: Simulation restart and from grab map simulation start bug fixed
fix: Sign in fail bug fix
ALS-1806
=> ALS 1806 simulation and sign in bug fixes

.github/workflows/build-android.yml, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/data_provider/DataProviderFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt, app/src/main/res/layout-sw600dp/bottom_sheet_map_style.xml, app/src/main/res/layout-sw720dp/bottom_sheet_map_style.xml
fix: Open data Map style selection with Ca-Central Stack bug fix
fix: Grab data map style selection from Southeast Asia Stack bug fix
fix: Node js version update for workflow
ALS-1806
=> ALS 1806 Map style change bug fixes

Gemfile.lock
fix: Gemfile updated for GitHub workflow
=> ALS-1806 Gemfile updated for github workflow

.github/workflows/build-android.yml
fix: Android build workflow update
=> ALS-1806 Android build workflow update

app/build.gradle, app/src/main/java/com/aws/amazonlocation/data/datasource/RemoteDataSourceImpl.kt, app/src/main/java/com/aws/amazonlocation/ui/base/BaseActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/region/RegionFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/analytics/AnalyticsUtils.kt, app/src/main/java/com/aws/amazonlocation/utils/providers/LocationProvider.kt, app/src/main/java/com/aws/amazonlocation/utils/providers/PlacesProvider.kt, app/src/main/java/com/aws/amazonlocation/utils/providers/RoutesProvider.kt, app/src/main/res/layout-sw600dp/bottom_sheet_direction_search.xml, app/src/main/res/layout-sw720dp/bottom_sheet_direction_search.xml, app/src/main/res/layout/bottom_sheet_direction_search.xml
fix: reverse geocode and direction button should not work if only data is pulled bug fixes
fix: Two bottom sheet opening fixes with code optimization
refactor: Auth SDK version update with related code changes
=> ALS-1882 Auth version updated and bug fixes

app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
feat: language support added to map
=> ALS-1889 language support added to map

app/src/main/java/com/aws/amazonlocation/utils/providers/PlacesProvider.kt
fix: Search result showing wrong distance bug fix
=> ALS-1913 Search result showing wrong distance bug fix

app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
fix: Portuguese and Chinese map language change not working bug fix
=> ALS-1889 Portuguese and Chinese map language change not working bug fix

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreViewModel.kt, app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleViewModel.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
fix: Set English as the first language in the language listing
fix: map language zh added as a second language when zh-Hant selected
=> ALS-1916 Map language fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt, app/src/main/java/com/aws/amazonlocation/utils/providers/PlacesProvider.kt
Fix: location is disabled, then the search should consider the center of the map
=> ALS-1969 Location is disabled then the search should consider the centre of the map

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
fix: Navigation Mode >Display forward direction icon and description title bar
fix: Navigation Mode >You’ve Arrived !! window not displayed on reaching the  destination
Here is the video of live navigation:
https://github.com/user-attachments/assets/7db3d6ca-b13f-487b-b73c-528479c87235
Here is the reaching and destination window:
=> ALS-1971, ALS-1973 Navigation Mode bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreViewModel.kt, app/src/main/java/com/aws/amazonlocation/utils/Constants.kt, app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt, app/src/main/res/values-ar/string.xml, app/src/main/res/values-de/string.xml, app/src/main/res/values-es/string.xml, app/src/main/res/values-fr/string.xml, app/src/main/res/values-hi/string.xml, app/src/main/res/values-it/string.xml, app/src/main/res/values-iw/string.xml, app/src/main/res/values-ja/string.xml, app/src/main/res/values-ko/string.xml, app/src/main/res/values-pt/string.xml, app/src/main/res/values-zh-rCN/string.xml, app/src/main/res/values-zh-rTW/string.xml, app/src/main/res/values/strings.xml
Fix: arrival time changed to 24 hours format, Palestine's represented wit abbreviation changed to PSE from PS, version year updated with 2025
<p>
</p>
=> ALS-2049 Bug fixes

app/src/main/java/com/aws/amazonlocation/ui/main/webView/WebViewActivity.kt, app/src/main/java/com/aws/amazonlocation/utils/ViewUtils.kt, app/src/main/res/layout-sw600dp/fragment_explore.xml, app/src/main/res/layout-sw720dp/fragment_explore.xml, app/src/main/res/layout/fragment_explore.xml, app/src/main/res/values-ar/string.xml, app/src/main/res/values-de/string.xml, app/src/main/res/values-es/string.xml, app/src/main/res/values-fr/string.xml, app/src/main/res/values-hi/string.xml, app/src/main/res/values-it/string.xml, app/src/main/res/values-iw/string.xml, app/src/main/res/values-ja/string.xml, app/src/main/res/values-ko/string.xml, app/src/main/res/values-pt/string.xml, app/src/main/res/values-zh-rCN/string.xml, app/src/main/res/values-zh-rTW/string.xml, app/src/main/res/values/strings.xml
=> ALS- 2057 Bug fixes

app/src/androidTest/java/com/aws/amazonlocation/GeneralUtils.kt, app/src/androidTest/java/com/aws/amazonlocation/ui/main/SimulationBackPressTest.kt, app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt, app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
fix: simulation back press not working bug fix
=> ALS-2058 Simulation back press not working bug fix

app/src/main/res/layout-sw600dp/bottom_sheet_start_simulation.xml, app/src/main/res/layout-sw720dp/bottom_sheet_start_simulation.xml, app/src/main/res/layout/bottom_sheet_start_simulation.xml
fix: start simulation bottom sheet layout cut issue solved
=> ALS-2057 Start simulation bottom sheet layout cut issue solved

app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt, app/src/main/res/layout-sw600dp/bottom_sheet_track_simulation.xml, app/src/main/res/layout-sw720dp/bottom_sheet_track_simulation.xml, app/src/main/res/layout/bottom_sheet_track_simulation.xml
Fix: simulation sheet scroll issue fixed
=> ALS-2059 Simulation sheet scroll issue fixed

README.md, app/build.gradle, custom.properties.example
fix: README.md and custom.properties.example files update
fix: version name and code update
=> ALS-2067 README.md & custom.properties.example files update and version code update

app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationListAdapter.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationNotificationAdapter.kt, app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
Fix: Notifications not appearing when the locale is set to the Arabic language have been fixed
=> ALS-2066 Notifications not appearing when the locale is set to the Arabic language have been fixed
